Repository framgia/sph_ui-ux-swipet, pull requests merged in 2022-04, with the labels that each got.

#2 [Task] Styles Config
  public/images/hero.png
  src/assets/css/button.css
  src/assets/fonts/Allison-Regular.ttf
  src/assets/fonts/Nunito-VariableFont_wght.ttf
  src/assets/tailwind.output.css
  tailwind.config.js
Labels: Fumihito approved

#5 [Task] Feature Section
  public/images/FeatureAdopt.png
  public/images/FeatureChat.png
  public/images/FeatureMatch.png
  public/images/FeatureProfile.png
  src/pages/Home.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/FeatureSection.js
  src/utilities/constants.js
  tailwind.config.js
Labels: Approved by Fumihito, Approved by Egie, Approved by Joash

#8 [Bugfix] Fix terminal errors and font weight
  src/pages/components/feature/FeatureSection.js
Labels: Approved by Fumihito, Approved by Egie, Approved by Charlotte

#7 [Task] Testimonials Section
  package-lock.json
  package.json
  public/images/Test00.jpg
  public/images/Test01.jpg
  public/images/Test02.jpg
  src/assets/css/testimonials.css
  src/assets/tailwind.output.css
  src/pages/Home.js
  src/pages/components/ChatBox.js
  src/pages/components/ContactUs.js
  src/pages/components/icons/NextIcon.js
  src/pages/components/icons/PreviousIcon.js
  src/pages/components/testimonial/Testimonial.js
  src/pages/components/testimonial/TestimonialCard.js
  src/utilities/constants.js
  tailwind.config.js
Labels: Approved by Fumihito, rose is reviewing

#10 [Task] Define common heading class
  src/assets/css/body-heading.css
  src/assets/css/button.css
  src/assets/tailwind.output.css
  src/pages/components/MainHeadline.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/FeatureSection.js
  src/pages/components/testimonial/Testimonial.js
  src/pages/components/testimonial/TestimonialCard.js
Labels: Approved by Fumihito, Approved by Charlotte

#11 [Task] Refactor file structure
  src/pages/Home.js
  src/pages/components/FeatureCard.js
  src/pages/components/feature/index.js
  src/pages/components/testimonial/index.js
Labels: Approved by Fumihito, Approved by Charlotte, needs rebase

#12 [Task] External Pages Section
  public/images/LogoBrown.svg
  src/assets/tailwind.output.css
  src/index.js
  src/pages/Home.js
  src/pages/components/MainHeadline.js
  src/pages/components/ScrollToTop.js
  src/pages/components/externalPages/AboutPage.js
  src/pages/components/externalPages/ExternalPageTemplate.js
  src/pages/components/externalPages/FaqPage.js
  src/pages/components/externalPages/PrivacyPolicyPage.js
  src/pages/components/externalPages/TermsAndConditionsPage.js
  src/pages/components/footerSection/FooterContent.js
  src/utilities/constants.js
  tailwind.config.js
Labels: Approved by Fumihito, Approved by Joash, Approved by Rose
