Repository framgia/sph_ui-ux-swipet, pull requests merged in 2022-05, with the labels that each got.

#15 [Bugfix] Fix Download Button Spacing
  src/pages/components/DownloadButton.js
  src/pages/components/MainHeadline.js
  src/pages/components/footerSection/index.js
Labels: Approved by Fumihito, Approved by Rose

#14 [improvements]-testionials_cards
  public/images/Test03.jpg
  public/images/Test04.jpg
  public/images/Test05.jpg
  src/assets/css/testimonials.css
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  src/utilities/constants.js
Labels: Approved by Fumihito, For Review, Approved by Charlotte, Approved by Rose

#16 [Task] Create a cookie policy pop up
  package-lock.json
  package.json
  src/index.js
  src/pages/Home.js
  src/pages/components/CookiePolicy.js
  src/pages/components/externalPages/ExternalPageTemplate.js
Labels: Fumihito is reviewing, Approved by Egie, Approved by Charlotte

#17 [Task] Add Swipet Animations
  package-lock.json
  package.json
  public/images/PawTrail.svg
  src/pages/components/MainHeadline.js
  src/pages/components/ScrollToTop.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/PawTrail.js
Labels: Approved by Fumihito, For Review, Approved by Charlotte, Approved by Joash

#20 [Task] Change default favicon and tab title
  package-lock.json
  package.json
  public/favicon.ico
  src/index.js
  src/pages/components/externalPages/AboutPage.js
  src/pages/components/externalPages/FaqPage.js
  src/pages/components/externalPages/PrivacyPolicyPage.js
  src/pages/components/externalPages/TermsAndConditionsPage.js
Labels: Approved by Fumihito, Approved by Rose

#18 [Task] Create 404 Page
  public/images/Dog404.png
  src/assets/css/button.css
  src/assets/tailwind.output.css
  src/index.js
  src/pages/components/CookiePolicy.js
  src/pages/components/externalPages/NotFound.js
Labels: Approved by Fumihito, For Review, rose is reviewing, Approved by Rose

#21 [Task] External Pages Target to New Tab
  src/pages/components/DownloadButton.js
  src/pages/components/footerSection/FooterContent.js
Labels: Approved by Fumihito, rose is reviewing

#24 [Bugfix] Fix Content Overflow on Mobile
  src/pages/Home.js
  src/utilities/constants.js
Labels: Approved by Fumihito, For Review, Approved by Charlotte

#23 [Task] Add meta description to pages
  public/index.html
  src/index.js
  src/pages/components/MetaDecorator.js
  src/pages/components/externalPages/AboutPage.js
  src/pages/components/externalPages/FaqPage.js
  src/pages/components/externalPages/NotFound.js
  src/pages/components/externalPages/PrivacyPolicyPage.js
  src/pages/components/externalPages/TermsAndConditionsPage.js
  src/utilities/constants.js
Labels: Approved by Fumihito, For Review, Approved by Rose

#19 [Task] Create Functionality for Chatbot
  package-lock.json
  package.json
  src/assets/css/chat-bubble.css
  src/assets/css/chatbot.css
  src/assets/tailwind.output.css
  src/pages/Home.js
  src/pages/components/ChatBox.js
  src/pages/components/ContactUs.js
  src/pages/components/chatbot/configs/ActionProvider.js
  src/pages/components/chatbot/configs/MessageParser.js
  src/pages/components/chatbot/configs/chatbotConfig.js
  src/pages/components/chatbot/index.js
  src/pages/components/chatbot/widgets/Options.js
  src/pages/components/chatbot/widgets/Process.js
  src/pages/components/chatbot/widgets/Requirements.js
  src/pages/components/chatbot/widgets/Topics.js
  src/utilities/constants.js
Labels: Approved by Fumihito, Approved by Joash, Approved by Rose

#25 [Bugfix] Header Picture is not tilted
  src/pages/components/MainHeadline.js
  src/pages/components/ScrollToTop.js
Labels: Approved by Fumihito, For Review, Approved by Egie, Approved by Charlotte, Approved by Joash

#26 [Bugfix] When user scroll up while open chat box, sometimes background is moving
  src/assets/css/chatbot.css
  src/pages/components/chatbot/widgets/Options.js
  src/pages/components/chatbot/widgets/Process.js
  src/pages/components/chatbot/widgets/Requirements.js
Labels: Fumihito is reviewing, For Review, Egie is reviewing

#28 [Task] Put links to logo
  src/pages/components/MainHeadline.js
  src/pages/components/footerSection/FooterContent.js
Labels: Approved by Fumihito, For Review, Approved by Egie

#29 [Bugfix] Empty message should not send in Chatbot
  src/pages/components/chatbot/configs/MessageParser.js
  src/pages/components/chatbot/index.js
Labels: Approved by Fumihito, Approved by Rose, Approved by Erick

#27 [Task] Image Optimization
  package-lock.json
  package.json
  public/images/Dog404.png
  public/images/Dog404.webp
  public/images/FeatureAdopt.webp
  public/images/FeatureChat.png
  public/images/FeatureChat.webp
  public/images/FeatureMatch.png
  public/images/FeatureMatch.webp
  public/images/FeatureProfile.png
  public/images/FeatureProfile.webp
  public/images/Hero.png
  public/images/Hero.webp
  public/images/Test00.jpg
  public/images/Test00.webp
  public/images/Test01.jpg
  public/images/Test01.webp
  public/images/Test02.jpg
  public/images/Test02.webp
  public/images/Test03.jpg
  public/images/Test03.webp
  public/images/Test04.jpg
  public/images/Test04.webp
  public/images/Test05.jpg
  public/images/Test05.webp
  src/pages/components/DownloadButton.js
  src/pages/components/MainHeadline.js
  src/pages/components/externalPages/ExternalPageTemplate.js
  src/pages/components/externalPages/NotFound.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/PawTrail.js
  src/pages/components/footerSection/FooterContent.js
  src/pages/components/testimonial/TestimonialCard.js
  src/utilities/constants.js
Labels: Approved by Fumihito, For Review, Approved by Rose

#30 [Task] Implement Prettier Tailwind CSS Plugin
  package-lock.json
  package.json
  src/assets/css/body-heading.css
  src/assets/css/button.css
  src/assets/css/chatbot.css
  src/assets/css/testimonials.css
  src/assets/tailwind.output.css
  src/pages/components/CookiePolicy.js
  src/pages/components/DownloadButton.js
  src/pages/components/MainHeadline.js
  src/pages/components/chatbot/configs/ActionProvider.js
  src/pages/components/chatbot/configs/chatbotConfig.js
  src/pages/components/chatbot/index.js
  src/pages/components/chatbot/widgets/Options.js
  src/pages/components/chatbot/widgets/Process.js
  src/pages/components/chatbot/widgets/Requirements.js
  src/pages/components/externalPages/AboutPage.js
  src/pages/components/externalPages/ExternalPageTemplate.js
  src/pages/components/externalPages/NotFound.js
  src/pages/components/externalPages/PrivacyPolicyPage.js
  src/pages/components/externalPages/TermsAndConditionsPage.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/PawTrail.js
  src/pages/components/footerSection/FooterContent.js
  src/pages/components/footerSection/index.js
  src/pages/components/icons/CloseIcon.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
Labels: Approved by Fumihito, For Review, rose is reviewing, Approved by Erick

#31 [Task] Dark Theme Feature
  public/images/BottomBanner.svg
  public/images/BottomBannerDark.svg
  public/images/ChatFloatingButtonDark.svg
  public/images/CloseFloatingButtonDark.svg
  public/images/Facebook.svg
  public/images/Instagram.svg
  public/images/LogoDarkTheme.svg
  public/images/Twitter.svg
  src/assets/css/body-heading.css
  src/assets/css/chatbot.css
  src/assets/css/testimonials.css
  src/pages/Home.js
  src/pages/components/DownloadButton.js
  src/pages/components/MainHeadline.js
  src/pages/components/chatbot/configs/chatbotConfig.js
  src/pages/components/chatbot/index.js
  src/pages/components/chatbot/widgets/Options.js
  src/pages/components/chatbot/widgets/Process.js
  src/pages/components/externalPages/ExternalPageTemplate.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/index.js
  src/pages/components/footerSection/FooterContent.js
  src/pages/components/footerSection/index.js
  src/pages/components/icons/FacebookIcon.js
  src/pages/components/icons/InstagramIcon.js
  src/pages/components/icons/TwitterIcon.js
  src/pages/components/testimonial/index.js
  src/utilities/hooks/useDarkMode.js
  tailwind.config.js
Labels: Approved by Fumihito, Approved by Egie, Approved by Joash, high prio

#36 [Bugfix] position of cookie policy
  src/pages/components/CookiePolicy.js
Labels: Fumihito is reviewing, For Review, Approved by Egie

#35 [Task] Update Font Styles
  src/assets/css/body-heading.css
  src/pages/components/MainHeadline.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/index.js
  src/pages/components/footerSection/FooterContent.js
  src/pages/components/footerSection/index.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  tailwind.config.js
Labels: Approved by Fumihito, For Review, Approved by Joash, Approved by Erick

#33 [Task] Implement Accordion in FAQ Page
  package-lock.json
  package.json
  src/pages/components/externalPages/AboutPage.js
  src/pages/components/externalPages/ExternalPageTemplate.js
  src/pages/components/externalPages/FaqPage.js
  src/pages/components/externalPages/PrivacyPolicyPage.js
  src/pages/components/externalPages/TermsAndConditionsPage.js
  src/pages/components/icons/CaretDown.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  src/utilities/constants.js
Labels: Approved by Fumihito, Approved by Rose, Approved by Erick

#32 [improvements] External Pages For Testimonials
  public/images/Avatar01.svg
  public/images/Test00.webp
  public/images/Test00A.webp
  public/images/Test00B.webp
  public/images/Test01.webp
  public/images/Test01A.webp
  public/images/Test01B.webp
  public/images/Test02A.webp
  public/images/Test02B.webp
  public/images/Test03A.webp
  public/images/Test03B.webp
  public/images/Test04A.webp
  public/images/Test04B.webp
  public/images/Test05A.webp
  public/images/Test05B.webp
  src/index.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContent.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContentTemplate.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialHeaderContent.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialMainContent.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  src/utilities/constants.js
Labels: Approved by Fumihito, For Review, Egie is reviewing, Approved by Erick

#39 [Task] Eslint Setup
  .eslintcache
  .eslintrc.json
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
  src/index.js
  src/pages/components/CookiePolicy.js
  src/pages/components/DownloadButton.js
  src/pages/components/MainHeadline.js
  src/pages/components/MetaDecorator.js
  src/pages/components/ScrollToTop.js
  src/pages/components/chatbot/configs/ActionProvider.js
  src/pages/components/chatbot/configs/MessageParser.js
  src/pages/components/chatbot/configs/chatbotConfig.js
  src/pages/components/chatbot/index.js
  src/pages/components/chatbot/widgets/Options.js
  src/pages/components/chatbot/widgets/Process.js
  src/pages/components/chatbot/widgets/Requirements.js
  src/pages/components/externalPages/AboutPage.js
  src/pages/components/externalPages/ExternalPageTemplate.js
  src/pages/components/externalPages/FaqPage.js
  src/pages/components/externalPages/PrivacyPolicyPage.js
  src/pages/components/externalPages/TermsAndConditionsPage.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContent.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContentTemplate.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialHeaderContent.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialMainContent.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/PawTrail.js
  src/pages/components/feature/index.js
  src/pages/components/footerSection/FooterContent.js
  src/pages/components/footerSection/index.js
  src/pages/components/icons/CaretDown.js
  src/pages/components/icons/CloseIcon.js
  src/pages/components/icons/FacebookIcon.js
  src/pages/components/icons/InstagramIcon.js
  src/pages/components/icons/NextIcon.js
  src/pages/components/icons/PreviousIcon.js
  src/pages/components/icons/TwitterIcon.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  src/reportWebVitals.js
  src/utilities/constants.js
  src/utilities/hooks/useDarkMode.js
Labels: Approved by Fumihito, Approved by Egie, Approved by Joash, Approved by Erick, high prio

#38 [Task] Dark Theme for Testimonials and 404 External Pages
  .eslintcache
  public/images/Avatar01dark.svg
  src/assets/css/button.css
  src/pages/components/externalPages/NotFound.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContent.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContentTemplate.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialHeaderContent.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialMainContent.js
  src/pages/components/footerSection/FooterContent.js
Labels: Approved by Fumihito, For Review, Approved by Egie, Approved by Joash

#41 [bugTask]-404_page_in_testimonial_external_pages
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContent.js
Labels: Approved by Fumihito, For Review, Approved by Egie, Approved by Erick

#42 [BugTask] Fix the position of the paw trail
  .eslintcache
  src/pages/components/feature/FeatureCard.js
Labels: Approved by Fumihito, For Review, Egie is reviewing, Approved by Joash

#37 [task]-testimonial-animation
  src/assets/css/testimonials.css
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  tailwind.config.js
Labels: Approved by Fumihito, For Review, Approved by Egie, Approved by Erick

#45 [BugTask] Fix Error When Sending Messages in Chatbot
  src/pages/components/chatbot/configs/MessageParser.js
Labels: Approved by Fumihito, For Review, Approved by Erick
