Repository framgia/sph_ui-ux-swipet, pull requests merged in 2022-06, with the labels that each got.

#47 [Task] Feature Detail Pages
  .eslintrc.json
  package-lock.json
  package.json
  public/images/ArrangeAMeetUp.webp
  public/images/Bingo.webp
  public/images/Chat.webp
  public/images/DiscoverPeople.webp
  public/images/GetVerified.webp
  public/images/ProcessRequirements.webp
  public/images/Profile.webp
  public/images/ShareYourJourney.webp
  public/images/Snow.webp
  public/images/Stitch.webp
  public/images/SwipeThatCatch.webp
  src/assets/css/body-heading.css
  src/index.js
  src/pages/Home.js
  src/pages/components/LanguageSelect.js
  src/pages/components/MainHeadline.js
  src/pages/components/feature/FeatureCard.js
  src/pages/components/feature/index.js
  src/pages/components/footerSection/FooterContent.js
  src/pages/components/footerSection/index.js
  src/pages/components/icons/CatIcon.js
  src/pages/components/icons/CheckCircledIcon.js
  src/pages/components/icons/CloseCircledIcon.js
  src/pages/components/icons/DogIcon.js
  src/pages/components/icons/IdeaIcon.js
  src/pages/components/icons/PetMatchIcon.js
  src/pages/components/icons/PetParentIcon.js
  src/pages/components/subscriptionSection/PlanCard.js
  src/pages/components/subscriptionSection/index.js
  src/pages/components/summarySection/SummaryCard.js
  src/pages/components/summarySection/index.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  src/pages/components/tipSection/Demo.js
  src/pages/components/tipSection/Tips.js
  src/pages/components/tipSection/index.js
  src/pages/featureDetail/index.js
  src/utilities/constants.js
Labels: Approved by Fumihito, Approved by Egie, Approved by Joash

#48 [Task] Add Translation Feature in Chatbot
  src/assets/locales/en/translation.json
  src/assets/locales/jp/translation.json
  src/i18n.js
  src/pages/components/LanguageSelect.js
  src/pages/components/chatbot/configs/ActionProvider.js
  src/pages/components/chatbot/configs/MessageParser.js
  src/pages/components/chatbot/configs/chatbotConfig.js
  src/pages/components/chatbot/index.js
  src/pages/components/chatbot/widgets/Process.js
  src/pages/components/chatbot/widgets/Requirements.js
  src/pages/components/chatbot/widgets/Topics.js
  src/utilities/constants.js
Labels: For Review, Approved by Rose, Approved by Erick

#49 [BugTask] Fix Footer banner color
  src/pages/components/footerSection/index.js
Labels: Approved by Fumihito, For Review, Approved by Rose

#50 task/heroImageAnimation
  package-lock.json
  package.json
  public/3DHero.gltf
  src/pages/components/MainHeadline.js
  src/pages/components/animation/Scene.js
  src/pages/components/animation/index.js
  yarn.lock
Labels: Approved by Fumihito, For Review, Approved by Rose, Approved by Erick

#51 [Task] Change Distorted Feature Images
  public/images/GetVerified.webp
  public/images/Profile.webp
  public/images/ShareYourJourney.webp
  public/images/SwipeThatCatch.webp
Labels: Approved by Egie, Approved by Joash, Approved by Rose

#52 [Task] Feature Detail Update images
  public/images/Corgi.webp
  public/images/Lilly.webp
  public/images/Marshall.webp
  public/images/Merry.webp
  public/images/Rolo.webp
  public/images/Sweetie.webp
  src/pages/components/testimonial/TestimonialCard.js
  src/utilities/constants.js
Labels: For Review, Approved by Egie, Approved by Rose

#55 [Bugfix] Button is broken in feature details pages
  public/images/Chat.webp
  src/pages/components/footerSection/index.js
Labels: Approved by Joash, Approved by Erick

#57 [Task] Feature Detail Page Dark Theme
  src/pages/components/icons/CatIcon.js
  src/pages/components/icons/CheckCircledIcon.js
  src/pages/components/icons/CloseCircledIcon.js
  src/pages/components/icons/DogIcon.js
  src/pages/components/icons/PetMatchIcon.js
  src/pages/components/icons/PetParentIcon.js
  src/pages/components/subscriptionSection/PlanCard.js
  src/pages/components/subscriptionSection/index.js
  src/pages/components/summarySection/SummaryCard.js
  src/pages/components/summarySection/index.js
  src/pages/components/testimonial/index.js
  src/pages/components/tipSection/Tips.js
  src/pages/components/tipSection/index.js
Labels: Approved by Fumihito, Approved by Egie, Approved by Erick

#56 [Task] Feature Detail Page Responsiveness
  src/assets/locales/en/translation.json
  src/pages/components/MainHeadline.js
  src/pages/components/subscriptionSection/PlanCard.js
  src/pages/components/subscriptionSection/index.js
  src/pages/components/summarySection/SummaryCard.js
  src/pages/components/summarySection/index.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  src/pages/components/tipSection/Tips.js
  src/pages/components/tipSection/index.js
Labels: Approved by Fumihito, rose is reviewing, Approved by Erick

#58 [Bugfix] Duplicate text is displayed
  src/assets/locales/jp/informations.json
  src/pages/components/externalPages/TermsAndConditionsPage.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialMainContent.js
Labels: Approved by Fumihito, For Review

#62 [Task] Carousel Testimonial Section
  src/assets/css/testimonials.css
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  tailwind.config.js
Labels: Approved by Fumihito, For Review, rose is reviewing, Approved by Joash

#61 Task_Include_Accept_Cookies_in_Feature_Details
  src/pages/components/externalPages/ExternalPageTemplate.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContent.js
  src/pages/featureDetail/index.js
Labels: Approved by Fumihito, For Review, Approved by Egie, Approved by Erick

#65 [Task] Admin Page Sidebar
  src/index.js
  src/pages/admin/AdminRoute.js
  src/pages/admin/Dashboard/index.js
  src/pages/admin/MySettings/index.js
  src/pages/admin/UserList/index.js
  src/pages/components/sidebar/SideBarData.js
  src/pages/components/sidebar/index.js
Labels: Approved by Fumihito, For Review, Approved by Erick

#68 Task/Admin My settings account tab
  src/pages/admin/MySettings/Account.js
Labels: For Review, Approved by Egie

#69 Task/Admin-Create-A-Modal-In-The-Location-Card
  package-lock.json
  package.json
  src/assets/css/body-heading.css
  src/assets/locales/en/places.json
  src/i18n.js
  src/pages/admin/Dashboard/StaticPlaces/PlacesContent.js
  src/pages/admin/Dashboard/StaticPlaces/index.js
  src/pages/admin/Dashboard/index.js
  src/pages/components/icons/DotsHorizontalIcon.js
  src/pages/components/icons/LocationIcon.js
  yarn.lock
Labels: Approved by Fumihito, For Review, Approved by Egie

#71 Task/admin markup create the remaining content of main page
  package-lock.json
  package.json
  src/assets/locales/en/adminFeatures.json
  src/i18n.js
  src/pages/admin/Dashboard/AdoptionOfPets/index.js
  src/pages/admin/Dashboard/StaticAnalytic/index.js
  src/pages/admin/Dashboard/StaticPlaces/PlacePercentage.js
  src/pages/admin/Dashboard/StaticPlaces/index.js
  src/pages/admin/Dashboard/index.js
  src/pages/components/icons/DogAndCatIcon.js
  src/pages/components/icons/InternetIcon.js
  src/pages/components/icons/PaperIcon.js
  src/pages/components/shared/Spinner.js
  src/pages/components/summarySection/SummaryCard.js
  yarn.lock
Labels: Approved by Fumihito, For Review, Approved by Egie

#73 task/pets-info
  src/index.js
  src/pages/Home.js
  src/pages/components/externalPages/PetsInfo/FactsAboutPetInfo.js
  src/pages/components/externalPages/PetsInfo/PetInfoTemplate.js
  src/pages/components/externalPages/PetsInfo/PetsDetails.js
  src/pages/components/externalPages/PetsInfo/PetsMyInfo.js
  src/pages/components/externalPages/PetsInfo/index.js
  src/pages/components/externalPages/TestimonialExternalPages/TestimonialContent.js
  src/pages/components/testimonial/TestimonialCard.js
  src/pages/components/testimonial/index.js
  src/pages/featureDetail/index.js
  src/utilities/constants.js
Labels: For Review, Approved by Egie
